apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Values.namespace.name | default .Release.Namespace | default "default" }}
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Values.namespace.name | default .Release.Namespace | default "default" }}
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: {{ .Release.Name }}-keycloak
        image: jboss/keycloak
        env:
        - name: KEYCLOAK_USER
          value: {{ .Values.master.username }}
        - name: KEYCLOAK_PASSWORD
          value: {{ .Values.master.password }}
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: {{ .Values.database.type }}
        - name: DB_ADDR
          value: {{ .Release.Name }}-{{ .Values.database.type }}.{{ .Values.namespace.name | default .Release.Namespace | default "default" }}.svc.cluster.local
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
