apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-keycloak-volume
  namespace: {{ .Values.namespace.name | default .Release.Namespace | default "default" }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/keycloak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-keycloak-pv-claim
  namespace: {{ .Values.namespace.name | default .Release.Namespace | default "default" }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}