apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Values.namespace.name | default .Release.Namespace | default "default" }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None